spring.application.name=meyvetakipsistemi

spring.datasource.url=jdbc:postgresql://localhost:5432/meyve_takip_sistemi
spring.datasource.username=postgres
spring.datasource.password=kante1967

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true