INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Ananas', 'ANANAS', 'ADET', '/fruits/ananas.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Armut Deveci', 'ARMUT-DEVECİ', 'KG', '/fruits/armut-deveci.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Armut Sante Maria', 'ARMUT-SANTE-MARİA', 'KG', '/fruits/armut-sante-maria.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Asma Yapragi', 'ASMA-YAPRAGİ', 'KG', '/fruits/asma-yapragi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Avakado', 'AVAKADO', 'KG', '/fruits/avakado.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Ayva', 'AYVA', 'KG', '/fruits/ayva.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Bal Kabagi', 'BAL-KABAGİ', 'ADET', '/fruits/bal-kabagi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Balik Sogan', 'BALİK-SOGAN', 'KG', '/fruits/balik-sogan.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Biber Carliston', 'BİBER-CARLİSTON', 'KG', '/fruits/biber-carliston.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Biber Dolma', 'BİBER-DOLMA', 'KG', '/fruits/biber-dolma.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Biber Kapya', 'BİBER-KAPYA', 'KG', '/fruits/biber-kapya.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Biber Sigicli', 'BİBER-SİGİCLİ', 'KG', '/fruits/biber-sigicli.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Biber Sivri', 'BİBER-SİVRİ', 'KG', '/fruits/biber-sivri.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Brokoli', 'BROKOLİ', 'KG', '/fruits/brokoli.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Cekirdeksiz Uzum', 'CEKİRDEKSİZ-UZUM', 'KG', '/fruits/cekirdeksiz-uzum.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Cennet Hurmasi', 'CENNET-HURMASİ', 'KG', '/fruits/cennet-hurmasi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Ceviz', 'CEVİZ', 'KG', '/fruits/ceviz.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Cilek', 'CİLEK', 'KG', '/fruits/cilek.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Cin Biberi', 'CİN-BİBERİ', 'KG', '/fruits/cin-biberi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Domates Antalya', 'DOMATES-ANTALYA', 'KG', '/fruits/domates-antalya.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Domates Ceri', 'DOMATES-CERİ', 'KG', '/fruits/domates-ceri.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Domates Pembe', 'DOMATES-PEMBE', 'KG', '/fruits/domates-pembe.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Domates Salkim', 'DOMATES-SALKİM', 'KG', '/fruits/domates-salkim.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Domates Yerli', 'DOMATES-YERLİ', 'KG', '/fruits/domates-yerli.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Ejder Meyvesi', 'EJDER-MEYVESİ', 'KG', '/fruits/ejder-meyvesi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Elma Amasya', 'ELMA-AMASYA', 'KG', '/fruits/elma-amasya.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Elma Kirmizi', 'ELMA-KİRMİZİ', 'KG', '/fruits/elma-kirmizi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Elma Pink', 'ELMA-PİNK', 'KG', '/fruits/elma-pink.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Elma Sari Golden', 'ELMA-SARİ-GOLDEN', 'KG', '/fruits/elma-sari-golden.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Elma Yesil', 'ELMA-YESİL', 'KG', '/fruits/elma-yesil.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Greyfurt', 'GREYFURT', 'KG', '/fruits/greyfurt.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Havuc Kirmizi', 'HAVUC-KİRMİZİ', 'KG', '/fruits/havuc-kirmizi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Havuc', 'HAVUC', 'KG', '/fruits/havuc.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Hindistan Cevizi', 'HİNDİSTAN-CEVİZİ', 'KG', '/fruits/hindistan-cevizi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('İspanak', 'İSPANAK', 'KG', '/fruits/ispanak.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('İstridye Mantari', 'İSTRİDYE-MANTARİ', 'KG', '/fruits/istridye-mantari.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kabak Ampul', 'KABAK-AMPUL', 'KG', '/fruits/kabak-ampul.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kabak', 'KABAK', 'KG', '/fruits/kabak.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Karnabahar', 'KARNABAHAR', 'ADET', '/fruits/karnabahar.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kereviz', 'KEREVİZ', 'KG', '/fruits/kereviz.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kestane', 'KESTANE', 'KG', '/fruits/kestane.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kivi', 'KİVİ', 'KG', '/fruits/kivi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kumkuat', 'KUMKUAT', 'KG', '/fruits/kumkuat.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Kuzu Kulagi', 'KUZU-KULAGİ', 'KG', '/fruits/kuzu-kulagi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Lahana Beyaz', 'LAHANA-BEYAZ', 'ADET', '/fruits/lahana-beyaz.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Lahana Bruksel', 'LAHANA-BRUKSEL', 'ADET', '/fruits/lahana-bruksel.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Lahana Kirmizi', 'LAHANA-KİRMİZİ', 'ADET', '/fruits/lahana-kirmizi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Limon', 'LİMON', 'KG', '/fruits/limon.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Mandalina', 'MANDALİNA', 'KG', '/fruits/mandalina.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Mantar Kestane', 'MANTAR-KESTANE', 'KG', '/fruits/mantar-kestane.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Mantar Kultur', 'MANTAR-KULTUR', 'KG', '/fruits/mantar-kultur.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Marul Duz', 'MARUL-DUZ', 'ADET', '/fruits/marul-duz.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Marul Kivircik', 'MARUL-KİVİRCİK', 'ADET', '/fruits/marul-kivircik.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Maydonoz', 'MAYDONOZ', 'KG', '/fruits/maydonoz.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Medine Hurmasi', 'MEDİNE-HURMASİ', 'KG', '/fruits/medine-hurmasi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Musmula', 'MUSMULA', 'KG', '/fruits/musmula.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Mut', 'MUT', 'KG', '/fruits/mut.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Muz İthal', 'MUZ-İTHAL', 'KG', '/fruits/muz-ithal.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Nane', 'NANE', 'KG', '/fruits/nane.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Nar', 'NAR', 'KG', '/fruits/nar.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Pancar Kirmizi', 'PANCAR-KİRMİZİ', 'KG', '/fruits/pancar-kirmizi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Patates', 'PATATES', 'KG', '/fruits/patates.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Patlican Kemer', 'PATLİCAN-KEMER', 'KG', '/fruits/patlican-kemer.png', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Patlican Topak', 'PATLİCAN-TOPAK', 'KG', '/fruits/patlican-topak.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Patlican Yamula', 'PATLİCAN-YAMULA', 'KG', '/fruits/patlican-yamula.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Pazi', 'PAZİ', 'KG', '/fruits/pazi.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Pirasa', 'PİRASA', 'KG', '/fruits/pirasa.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Portakal Sikma', 'PORTAKAL-SİKMA', 'KG', '/fruits/portakal-sikma.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Portakal Washington', 'PORTAKAL-WASHİNGTON', 'KG', '/fruits/portakal-washington.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Poset', 'POSET', 'KG', '/fruits/poset.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Reyhan', 'REYHAN', 'KG', '/fruits/reyhan.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Roka', 'ROKA', 'KG', '/fruits/roka.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Salatalik', 'SALATALİK', 'KG', '/fruits/salatalik.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sarimsak', 'SARİMSAK', 'KG', '/fruits/sarimsak.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sogan Arpacik', 'SOGAN-ARPACİK', 'KG', '/fruits/sogan-arpacik.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sogan Beyaz Kuru', 'SOGAN-BEYAZ-KURU', 'KG', '/fruits/sogan-beyaz-kuru.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sogan Gumus', 'SOGAN-GUMUS', 'KG', '/fruits/sogan-gumus.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sogan Kuru Mor', 'SOGAN-KURU-MOR', 'KG', '/fruits/sogan-kuru-mor.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Sogan Yesil', 'SOGAN-YESİL', 'KG', '/fruits/sogan-yesil.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Tere', 'TERE', 'KG', '/fruits/tere.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Turp Daylon', 'TURP-DAYLON', 'KG', '/fruits/turp-daylon.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Turp Gapon', 'TURP-GAPON', 'KG', '/fruits/turp-gapon.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Turp Siyah', 'TURP-SİYAH', 'KG', '/fruits/turp-siyah.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Yer Elmasi', 'YER-ELMASİ', 'KG', '/fruits/yer-elmasi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Yer Fistigi', 'YER-FİSTİGİ', 'KG', '/fruits/yer-fistigi.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Yerli Muz', 'YERLİ-MUZ', 'KG', '/fruits/yerli-muz.jpg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Yumurta 30 Lu', 'YUMURTA-30-LU', 'ADET', '/fruits/yumurta-30-lu.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Zencefil', 'ZENCEFİL', 'KG', '/fruits/zencefil.jpeg', true, true);
INSERT INTO public.fruits (name, code, unit, image_path, is_active, is_perishable) VALUES ('Zerdecal', 'ZERDECAL', 'KG', '/fruits/zerdecal.jpeg', true, true);
